version: '3.9'


services:
  django_app:
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - advert_db
    env_file:
      - .env
    ports:
      - "8090:8000"
    restart: always

  advert_db:
    container_name: advert_db
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5434:5432"
    volumes:
      - './advert_db:/var/lib/postgresql/data'
    restart: always

volumes:
  advert_db: